function [ CellCoeff ] = SamplingCoeff_AllN( L,fVals,Points,Nmax,Proldat,truncvec,flag )
% This function computes the sampling series coefficients for all degrees
% of GPSWFs up to Nmax.
%
%   Input - L : Sampling frequency
%           fVals : Evaluations of a function on a set of points
%           Points : Sampling points
%           Nmax : Maximal degree of radial GPSWFs
%           Proldat : Cell array generated by Lederman's code for all
%                     values in Narray.
%           flag : 0 - if the code is used for construction of coefficients
%                  1 - if the code is used for approximating a value.
%
%   Output - CellCoeff : Matrix which contains all the coefficients of
%                        the sampling series, appering in the
%                        approximation.


%%%%%%%%%%% Part 1 - costruct coefficients matrix %%%%%%%%%%%%%%%
shcount = [1:2:(2*Nmax+1)];
numprols =dot(truncvec,shcount);
CellCoeff = zeros(numprols,1);
pos = 1;

%%%%%%%%%% Part 2 - Generate and save coefficients %%%%%%%%%%%%%%
for j = 0:Nmax
    
   truncationparam = truncvec(1,j+1);
   allcoeffs = SamplingCoeff_N( L,fVals,Points,j,Proldat{1,j+1}, Proldat{2,j+1}, Proldat{3,j+1},truncationparam,flag);
   CellCoeff(pos:(pos+length(allcoeffs)-1),1)= allcoeffs;
   pos = pos+length(allcoeffs);
   
end


end

