function [ Coeff ] = ComputeCoeff_Example( radind,sphind,ProlatesEval,fVals,eig,N )
% This function computes the sampling coefficient corresponding to radind
% and sphind
%
%   Input - radind : Index of radial GPSWF
%           sphind : Index of spherical harmonic
%           ProlatesEval : data array generated by EvalProlGrid_fixedN
%           fvals : Vector of function evaluations multiplied by 1/L^3
%
%   Output - Coeff : The desired coefficient (see (52) in our paper)

pos  = (radind-1)*(2*N+1)+sphind;

GPSWFVec = conj(eig(1,radind)*ProlatesEval_Example(pos,:));

Coeff = GPSWFVec*fVals;

end

